# Generated by Django 5.1.7 on 2025-03-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_certificate_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='file',
        ),
        migrations.AddField(
            model_name='certificate',
            name='file_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
